import Vue from "vue"

import {
    TreeSelect,
    Button,
    Tab,
    Tabs,
    DropdownMenu,
    DropdownItem,
    Calendar,
    Cell,
    Card,
    Search,
    Icon,
    Swipe,
    SwipeItem,
    Grid,
    GridItem,
    Lazyload,
    List,
    IndexBar,
    Loading,
    Skeleton,
    IndexAnchor,
    NavBar,
    Image as VanImage,
} from "vant"
;[
    Button,
    Tab,
    Tabs,
    DropdownMenu,
    DropdownItem,
    Cell,
    Calendar,
    Card,
    Search,
    Icon,
    Swipe,
    SwipeItem,
    Grid,
    GridItem,
    List,
    NavBar,
    IndexBar,
    IndexAnchor,
    TreeSelect,
    VanImage,
    Loading,
    Skeleton,
].forEach((item) => Vue.use(item))

Vue.use(Lazyload, {
    attempt: 5,
    preload: "1.3",
    lazyComponent: true,
    loading: "http://gw.alicdn.com/tfs/TB1ielmpoT1gK0jSZFrXXcNCXXa-128-128.ico",
})
